---

- hosts: all
  become: true
  pre_tasks:

  - name: Install Update - Ubuntu
    tags: always
    apt:
      update_cache: yes
      upgrade: dist
    when: ansible_distribution == "Ubuntu"

  - name: Install Update - CentOS
    tags: always
    dnf:
      update_only: yes
      update_cache: yes
    when: ansible_distribution == "CentOS"

- hosts: web
  become: true
  tasks:

  - name: install apache and php packages
    tags: apache, apche2, httpd, web
    package:
      name:
        - "{{ apache_package }}"
        - "{{ php_package }}"
      state: latest
      update_cache: yes

- hosts: db
  become: true
  tasks:

  - name: Install MariaDB
    tags: mariadb, db
    package:
      name:
        - "{{ db_package }}"
      state: latest

- hosts: file
  become: true
  tasks:

  - name: Install Samba
    tags: samba, file
    package:
      name:
        - samba
      state: latest
